### ISSUE TITLE
app无法连接服务，终端报错

### ISSUE THREAD

**Issue by NanoRocky** [hyperzlib/DG-Lab-Coyote-Game-Hub#7]
我试了 0.9.0 和 1.0.0 beta ，都会这样。app 提示超时，终端报错，网页端波形转不出来（可能是未连接）。
`Uncaught exception: TypeError: route.regexp.test is not a function
    at WebSocketRouter.match (\server\utils\WebSocketRouter.js:20:30)
    at WebSocketServer.<anonymous> (\server\utils\websocket.js:8:35)
    at WebSocketServer.emit (node:events:519:28)
    at WebSocketServer.completeUpgrade (\node_modules\ws\lib\websocket-server.js:436:5)
    at WebSocketServer.handleUpgrade (\node_modules\ws\lib\websocket-server.js:344:10)
    at Server.upgrade (\node_modules\ws\lib\websocket-server.js:119:16)
    at Server.emit (node:events:519:28)
    at onParserExecuteCommon (node:_http_server:939:14)
    at onParserExecute (node:_http_server:840:3)`

**Comment by NanoRocky** [comment]
噢，好了，我稍微改了一下下（

`"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.WebSocketRouter = void 0;
const path_to_regexp_1 = require("path-to-regexp");

class WebSocketRouter {
    routes; // 保存路由信息

    constructor() {
        this.routes = [];
    }

    get(url, callback) {
        // 使用 path-to-regexp 的 match 方法来生成匹配器
        const matcher = (0, path_to_regexp_1.match)(url, { decode: decodeURIComponent });
        this.routes.push({
            url,
            matcher,
            callback
        });
    }

    match(url) {
        // 遍历所有路由，尝试匹配
        for (const route of this.routes) {
            const matchResult = route.matcher(url); // 使用 matcher 进行匹配
            if (matchResult) {
                // 提取路由参数
                let routeParams = matchResult.params || {};
                
                // 返回匹配的路由和参数
                return {
                    route,
                    params: routeParams
                };
            }
        }

        // 如果没有匹配，返回 null
        return null;
    }
}

exports.WebSocketRouter = WebSocketRouter;
`
